<?php
/**
 * Custom routes (SAFE — survives updates)
 * Static routes: '/path' => '/pages/file.php'
 * Dynamic patterns: '__patterns' => [regex, target, params]
 *
 * Category-routes are auto-generated by CMS admin (/categories).
 */
return [

    '__patterns' => [
    ],
];
